/* eslint-disable no-dupe-keys */
const mapper = {
  'Apellido 1': 'firstLastName',
  'Apellido 2': 'secondLastName',
  Nombres: 'name',
  'Cargo que busca': 'candidacy',
  Departamento: 'department',
  Ciudad: 'city',
  Territorio: 'territory',
  'Cargo ficha tarjetón': 'chargeCard',
  Twitter: 'twitterHandle',
  'Posición izq/der': 'position',
  Género: 'gender',
  Partido: 'party',
  Coavales: 'coavales',
  'Número de lista': 'listNumber',
  'Rango de edad': 'age',
  'Posición frente al Gobierno Petro': 'positionAgainstThePetroGovernment',
  'Nivel de estudios': 'educationLevel',
  'Sector del que viene': 'backgroundSector',
  'Voto segunda vuelta 2022': 'secondRoundVote2022',
  'Es polémico': 'isPolemic',
  'Ha ocupado un cargo público': 'hasHeldPublicOffice',
  'Fórmula a la Gobernación': 'candidateForTheGovernorship',
  'Fórmula a la Alcaldía': 'mayoralCandidate',
  Banderas: 'flags',
  'Aborto legal hasta los 6 meses de embarazo': 'legalAbortionUpToSixMonthsOfPregnancy',
  'Se deben regular medios de comunicación': 'theMediaShouldBeRegulated',
  'Que las JAC ejecuten obras públicas grandes': 'thatTheJACExecuteLargePublicWorks',
  'EPS deben manejar recursos públicos': 'EPSMustManagePublicResources',
  'Se debe frenar la exploración petrolera': 'oilExplorationMustBeStopped',
  'Subir impuesto predial': 'increasePropertyTax',
  'Tiene líos o cuestionamientos': 'hasProblemsOrQuestions',
  Perfil: 'profile',
  Foto: 'photo',
  'LGBTIQ+': 'lgbtiq',
  '¿Pertenece a una comunidad étnica, raizal o indígena?': 'belongsCommunity',
  'Posición frente a al alcalde actual': 'currentMayorPosition',
  'Favorabilidad Bukele': 'bukeleFavorability',
  'Número de lista': 'electoralNumber',
};

export default mapper;
