const mapper = {
  'Apellido 1': 'firstLastName',
  'Apellido 2': 'secondLastName',
  Nombres: 'name',
  Departamento: 'department',
  TipoDoc: 'docType',
  Número: 'docNumber',
  'Perfil de quien es quien': 'externalProfileURL',
  Twitter: 'twitterHandle',
  'Página web': 'website',
  'Correo electrónico': 'email',
  'Votos más recientes': 'recentVotes',
  'En qué elección sacó los votos más recientes': 'electionOfRecentVotes',
  'Año de nacimiento': 'yearOfBirth',
  Cámara: 'office',
  Género: 'gender',
  Comisión: 'commission',
  Partido: 'party',
  'Número en el tarjetón': 'electoralNumber',
  'Posición iz/der': 'position',
  'Subregión provincia o localidad': 'province',
  'Profesión u oficio': 'profession',
  'Estudios más altos': 'higherDegree',
  'Sector del que viene': 'backgroundSector',
  'Experto en': 'areaOfExpertise',
  'Ha sido condenado': 'hasBeenConvicted',
  'Ha sido investigado': 'hasBeenInvestigated',
  'Ha sido destituido': 'hasBeenDismissed',
  'Ha sido congresista': 'hasBeenMemberOfCongress',
  'Períodos como congresista': 'termsAsMemberOfCongress',
  'Ha sido gobernador': 'hasBeenGovernor',
  'Ha sido diputado': 'hasBeenDeputy',
  'Ha sido alcalde': 'hasBeenMayor',
  'Ha sido concejal': 'hasBeenCityCouncillor',
  'Había sido candidato a cargos de elección popular':
    'hasBeenCandidateForElectedOffice',
  'Ha estado en más de dos partidos': 'hasBeenInMoreThanTwoParties',
  'Ha ocupado un cargo público': 'hasHeldPublicOffice',
  'Heredero de votos de condenados': 'heirToDoomedVows',
  'Heredero de votos de investigados': 'heirToVotesUnderInvestigation',
  Cuestionado: 'questioned',
  'Tiene familiar en la política': 'hasFamilyInPolitics',
  'Es heredero político': 'isPoliticalHeir',
  Perfilito: 'profile',
  Foto: 'photo',
  'Busca reelección': 'seeksReelection',
  'Salto Camara - Senado': 'fromChamberToSenate',
  'Precandidato que apoyaba': 'supportedPrecandidate',
  'Candidato presidencial que apoya': 'supportedPresidentialCandidate',
  'Bandera 1': 'firstFlag',
  'Bandera 2': 'secondFlag',
  'Bandera 3': 'thirdFlag',
  'Es afro': 'isAfro',
  'Fórmula al Senado': 'senateFormula',
  'Fórmula a la Cámara 1': 'firstChamberFormula',
  'Fórmula a la Cámara 2': 'secondChamberFormula',
  'Fórmula a la Cámara 3': 'thirdChamberFormula',
  Edad: 'age',
  'Nivel de estudios': 'educationalLevel',
  'Tiene líos o cuestionamientos': 'hasQuestioning',
  'Tiene experiencia en el Estado': 'hasExperienceInNation',
  'Es de una minoría': 'belongsToMinority',
  'Grupo que representa': 'groupThatRepresents',
  Circunscripción: 'district',
  'Ha recibido amenazas': 'hasReceivedThreats',
  'Tipo de circunscripción': 'districtType',
  Pendiente: 'pending',
  'Posición frente al Gobierno Duque': 'positionTowardsGovernment',
  'Perfil corto para BOT': 'imageProfile',
  Electo: 'elected',
  Votación: 'totalVotes',
  // Presidential specific
  'Mentiras y verdades chequeadas': 'liesAndVerifiedTruths',
  Consulta: 'coalition',
  Aval: 'guarantee',
  'Lugar de nacimiento': 'placeOfBirth',
  'Ha sido gobernador o alcalde': 'hasBeenGovernorOrMayor',
  'Se había lanzado antes a la Presidencia': 'hadPreviouslyRunForThePresidency',
  '¿QUÉ PIENSA? Voto en el plebiscito': 'voteInThePlebiscite',
  'Despenalizar el aborto': 'decriminalizingAbortion',
  'Máximo de personas a su cargo': 'maximumNumberOfDependents',
  'Responsabilidad de decisiones determinantes para el país':
    'responsibilityForDecisiveDecisionsForTheCountry',
  'Oposición o apoyo Gobierno Duque': 'oppositionOrSupportToGovernment',
  'Subir el impuesto al patrimonio': 'raisingTheWealthTax',
  'Máximo cargo en el Ejecutivo': 'highestPositionInTheExecutive',
  'Máximo cargo en el sector privado': 'highestPositionInThePrivateSector',
  'Apoyó el Paro': 'supportedTheStrike',
  'Obligar a funcionarios públicos a vacunarse':
    'forcingPublicOfficialsToGetVaccinated',
  'Favorabilidad con la que terminó el más alto y reciente cargo ejecutivo':
    'mostRecentFavorability',
  'FÓRMULA VICEPRESIDENCIAL Nombre fórmula': 'vicepresident',
  'Link perfil fórmula': 'vicepresidentProfileLink',
  'Foto fórmula': 'vicepresidentPhoto',
  'Adopción por parte de parejas el mismo sexo': 'adoptionBySameSexCouples',
  'Impuesto a las iglesias': 'churchTax',
  'Aumentar la edad de pensión': 'increasePensionAge',
  'Volver al glifosato': 'backToGlyph',
  Fracking: 'fracking',
  'Regular la marihuana recreativa': 'regulateMarijuana',
  'Fallo sobre el aborto': 'rulingOnAbortion',
  // Primera vuelta presidencial
  'QUÉ PROPONE Sus propuestas bomba:': 'majorProposals',
  'Saber más.': 'majorProposalsAbout',
  'Carretómetro a su bandera:': 'lieMesaure',
  'Link carretómetro (ponerlo en donde dice sus propuestas para tk)': 'lieMeasureAbout',
  'CÓMO GOBERNÓ Favorabilidad al final de su alcaldía:': 'favorabilityAsMajor',
  'Gobernó con:': 'governWith',
  'Talante:': 'frameOfMind',
  'Gerencia:': 'management',
  'Relación con otros poderes:': 'relationWithOtherPowers',
  'Logros:': 'achievements',
  'Video embebido': 'video',
  'Saber más como gobernó:': 'governAbout',
  'SOMBRAS Su mayor lunar:': 'greaterMole',
  'Link su mayor lunar (ponerlo en la frase no como sabber más)': 'greaterMoleAbout',
  'Encarna el riesgo de:': 'riskOf',
  'Link (ponerlo en la primera parte de la frase del riesgo que encarnana)': 'riskOfAbout',
};

export default mapper;
