name: update

on:
  repository_dispatch:
    types: [on-demand]

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update data files
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install frontend deps
        run: npm i
      - name: Install scripts deps
        run: |
          cd scripts
          npm i
      - name: Fetch and transform data
        run: node scripts/transform.js
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Update data [gh-action]"
          git push